FROM registry.access.redhat.com/ubi8/ubi:latest

ENV OCPVERSION="4.5.2"

ENV OCPRHCOSVERSION="4.5.6"

ENV HELPERPODVERSION="2.4.5.0"

RUN dnf -y install tftp-server syslinux wget jq python3-pip && \
    pip3 install ansible

COPY files/default.j2 /usr/local/src/
COPY files/pxe-bootstrap.j2 /usr/local/src/
COPY files/pxe-master.j2 /usr/local/src/
COPY files/pxe-worker.j2 /usr/local/src/

COPY scripts/startup.sh /usr/local/bin/

EXPOSE 69/udp

ENTRYPOINT ["/usr/local/bin/startup.sh"]
