FROM centos:centos8

ENV OCPVERSION="4.6.1"

ENV OCPRHCOSVERSION="4.6.1"

ENV HELPERPODVERSION="2.4.6.0"

RUN dnf -y install tftp-server syslinux wget jq python3-pip && \
    pip3 install ansible yq

COPY files/pxe-bootstrap.j2 /usr/local/src/
COPY files/pxe-master.j2 /usr/local/src/
COPY files/pxe-worker.j2 /usr/local/src/

COPY scripts/startup.sh /usr/local/bin/

EXPOSE 69/udp 69/tcp

ENTRYPOINT ["/usr/local/bin/startup.sh"]
